### PR TITLE
Added google-java-format and pom-tidy format hook to maven build

### PR DESCRIPTION
**Pull request by craigatgoogle**
Added maven hook for running google-java-format: https://github.com/coveo/fmt-maven-plugin
Added maven hook for running pom tidy: http://www.mojohaus.org/tidy-maven-plugin/

### CODE REVIEW

**Comment by evandbrown** [comment]
Will need a rebase before merging, otherwise LGTM!

**Comment by rachely3n** [comment]
Ah, yes, I had meant to approve this, but was wondering what the best course of action was to merge everything since the cleanup affects a good number of files/lines.

**Comment by evandbrown** [comment]
@craigatgoogle Mind rebasing and pushing, then we'll merge?

**Comment by ingwarsw** [comment]
@evandbrown @rachely3n It will break all other PRs.. merging them will be nightmare.
Mine are complicated a bit.. and this one can be merged anytime.. when no big PRs will be done..

Can we wait with it?

**Comment by craigatgoogle** [comment]
This PR isn't crucial, so it can wait. It'll be easier to close this and re-open once we're ready for it.

**Pull request closed without merging**
