### PR TITLE
Release 2.0.0 changelog

### PR DESCRIPTION
**Pull request by rachely3n**
Change log for new release.

### CODE REVIEW

**Comment by evandbrown** [comment]
We're changing the min supported version, so I think this could be considered a major version bump (semver.org). @rachely3n @craigatgoogle thoughts?

**Comment by rachely3n** [comment]
O I see... that does sound more like a major version change.

**Comment by ingwarsw** [comment]
Personally I would say that MINOR version should be fixed.
For sure this version add new functionality.

And about MAJOR version, Im not sure.. I would say its not incompatible change..

**Comment by craigatgoogle** [comment]
Assuming we're using semvar: https://semver.org/spec/v2.0.0.html
Then since this will potentially break users running older versions of Jenkins, then technically it's not a backwards compatible change. This would imply a major version change.

**Comment by evandbrown** [comment]
@rachely3n let's do 2.0.0 and I'll merge/release.

**Comment by rachely3n** [comment]
Done.

**Pull request merged**
