### PR TITLE
Allow specifying extra google-labels

### PR DESCRIPTION
**Pull request by darashenka**

### CODE REVIEW

**Comment by ingwarsw** [comment]
@evandbrown Im not sure who is maintainer of that plugin but there are many PRs that are not getting merged for whatever reason and they would help a lot.. (thats one of them)

Could you please take care about them?
At that moment it looks like that project is abandoned.. or at least forgot...

If the PR code is bad just please say so.. or if the future is not going to me merged because of some reason also say so..

**Comment by evandbrown** [comment]
Hey Karol,

We've got a few folks getting up to speed on the plugin. Most of the work
has been happening in #10 and #2. Work will be completed on those in the
next few days and these other PRs will be addressed. Sorry for the delay.

Thanks,

Evan

**Comment by ingwarsw** [comment]
I just tested in od production cause we had new request from OPS team to add labels..
And it works like a charm...

Probably adding some tests for those test cases would be perfect tho..

**Comment by ingwarsw** [comment]
After further testing it seems like label values are lost at GUI..

But still labels are correctly applied...

**Comment by ingwarsw** [comment]
Here is commit that fixes this issue..
https://github.com/ingwarsw/google-compute-engine-plugin/commit/8ededb0bcfbbf5cc1cae332eac5bc734a2e93897

**Comment by ingwarsw** [comment]
@rachely3n @craigatgoogle Actually Im changing template pr #12 to add template labels on top of internal needed labels.. 
After that it will cover all functionality of that PR..

Do you think it will be still needed?

**Comment by rachely3n** [comment]
We will release https://github.com/jenkinsci/google-compute-engine-plugin/pull/12/files soon, and we can then close this one out potentially.

**Comment by rachely3n** [comment]
I'm closing this PR for now since google labels will be available via templates.

**Pull request closed without merging**
