### PR TITLE
 Add support for Windows instances and local SSDs on Google Cloud 

### PR DESCRIPTION
**Pull request by hach-que**
I've already signed the CLA.

## Windows Instances

This adds support for running Windows instances on Google Cloud over SSH. Instructions on how to set up the Windows instances are provided in the help text for the "Windows?" checkbox for the instance configuration. Minimum requirements are:

* Java
* OpenSSH Server for Windows
* Preconfigured Username / Password

These requirements can be set up using the Startup Script field, which uses the PowerShell Startup Scripts for Windows when the instance is configured to be a Windows VM.

## Local SSDs

This also adds support for attaching local SCSI-based SSDs. For Windows instances, it automatically initialises the disks and mounts them to ensure they're available for the Jenkins agent. For Linux instances, users need to initialise and mount the disks using a startup script.

## Remote Workspace Location

Users can now also configure the remote workspace location. This is primarily intended to be used with Local SSDs so that the workspace can be moved to a local SSD. If it's left blank, it defaults to either `C:\JenkinsSlave` or `./.jenkins-slave` based on the instance operating system.

### CODE REVIEW

**Comment by hach-que** [comment]
@evandbrown Can you please review this change?

**Comment by ingwarsw** [comment]
@hach-que Thats huge 👍 
I thought that Im only one trying to set up windows slaves by that plugin but seems im not..

I will try to build plugin and test in manually on our servers now..

**Comment by dansheme** [comment]
I installed the version from hach-que:master and it works perfectly. Thanks!

**Comment by sprsquish** [comment]
This is exactly what I need! Any update on its status?
Thank you.

**Comment by rachely3n** [comment]
@hach-que I'm currently writing integration tests for this PR.

I just have a few questions:
- Were you able to launch the instances and have them install openSSH Server via the startup script?
- What images were running on your instances
- How did you run/test your feature

Thanks

**Comment by hach-que** [comment]
Yeah, I was able to get the OpenSSH server installed using the startup script example provided, though in our actual setup we pre-bake the images with Packer.

You should just be able to use the Windows Server images on Google Cloud.

I tested it by just building and debugging in Eclipse(?) and configuring that Jenkins instance to launch Windows instances on Google Cloud. Then once I had it working there I uploaded the plugin to our actual Jenkins instance.

**Comment by hach-que** [comment]
This is the script we use in Packer to configure OpenSSH:

```
Write-Output "Setting execution policy for PowerShell scripts...";
Set-ExecutionPolicy Bypass -Scope Process -Force;

Write-Output "Installing Chocolatey...";
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

Write-Output "Refreshing environment...";
RefreshEnv.cmd

Write-Output "Installing OpenSSH Server..."
choco install -y openssh -params '"/SSHServerFeature"'
if ($LastExitCode -ne 0) {
    exit 1
}

Write-Output "Adding build user..."
net user /add SOMEUSER SomePasswordThatMeetsWindowsRequirements1234
net localgroup administrators SOMEUSER /add
```

Then configuring the plugin to connect with `SOMEUSER` and the password.

**Comment by hach-que** [comment]
Yeah I was able to use the "Startup script" configuration to install Chocolatey and OpenSSH so that the build agent would start up from a default GCE Windows image. It probably wasn't exactly the PowerShell script I pasted above, but it would have been to the same effect - installing OpenSSH via Chocolatey.

**Comment by rachely3n** [comment]
@ingwarsw do you mean this current PR?

We cannot merge the PR yet since we now have some security concerns regarding authenticating with windows username and password. Furthermore, the username and password would be stored in the Jenkins Config, which would not be very secure. We are currently trying to authenticate in a different way.

However, if you still wish to use this PR, you will have to manually merge the changes. If you look in the commit history, the main things that would cause conflict for you are minCPUPlatform was added and I updated the integration test. I believe it would not be too difficult to merge.

**Comment by hach-que** [comment]
I was originally going to make it authenticate using the compute instance's generated Windows password, but it turns out that logic is super custom and not handled by any of the gcloud libraries, so I went with the fixed password instead.

You could alternatively prepend the generation of the SSH private keys to the startup script, and use those to authenticate through OpenSSH. However, that has to be an option because different customers will set up their Windows instances differently, and the invocations and command line of doing that generation will be different under different environments.

Regardless of if you offer more secure options though, you will still need to offer a fixed username/password option since this is the majority of how the Windows world works.

**Comment by rachely3n** [comment]
@hach-que Yes, my windows experience is fairly limited, but right now I'm exploring how viable it would be for me to programmatically change the compute engine instance's password to authenticate SSH. 

However, are you still suggesting that even if I change the password for the instance, I should still offer a fixed username/password option that the user can choose to configure?

**Comment by hach-que** [comment]
You should definitely have it as an option. Since fixed username/password is the way it works on the EC2 plugin, and there's always the chance someone is using something esoteric like Cygwin SSHd instead of Microsoft's OpenSSH Server (where command invocation works differently), you'll need fixed username/password as an option for those kinds of scenarios.

That said, I think you could probably provide a couple of different options like:
- Generated public/private keypair
- Generated password
- Fixed username/password

For the first two options, you'll still need to ask the user in configuration for the username they want to use, because not everyone wants to use Administrator (or they might have installed software under a specific account).

**DISCLAIMER:** I haven't tested the scripts below. I'll see if I can find some time in the next few weeks to go through and test them.

## Generated public/private keypair

This is the most secure option of the three; we automatically generate a public/private keypair for SSH when starting the instance, and use the startup script to update `authorized_keys` on the agent as it starts.

### Full automated setup

For when the user wants to use a Windows GCE image that isn't configured with OpenSSH:

```
# Should be the Windows account username as specified by the user.
$ConfiguredUsername = "<INJECT VALUE HERE>"
# Should be like "ssh-rsa AAAA..." or whatever the line to be inserted into authorized_keys should be.
$ConfiguredPublicKey = "<INJECT VALUE HERE>"

if (!(Test-Path "$env:SYSTEMDRIVE\_GCE_Jenkins_FirstPhase.txt")) {
  # We are in the first phase where we need to configure PowerShell, install Chocolately, install the OpenSSH Server and the restart the VM.

  Write-Output "Setting execution policy for PowerShell scripts...";
  Set-ExecutionPolicy Bypass -Scope Process -Force;

  Write-Output "Installing Chocolatey...";
  Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

  Write-Output "Refreshing environment...";
  RefreshEnv.cmd

  Write-Output "Installing OpenSSH Server..."
  choco install -y openssh -params '"/SSHServerFeature /KeyBasedAuthenticationFeature"'
  if ($LastExitCode -ne 0) {
    exit 1
  }

  Write-Output "Creating file for next phase on reboot..."
  Set-Content -Path "$env:SYSTEMDRIVE\_GCE_Jenkins_FirstPhase.txt" -Value "OK"

  Write-Output "Restarting the VM..."
  shutdown /t 0 /f /r
} else {
  # We are in the second phase of startup where we need to set up authorized_keys for the specified user.
  $UserSid = (New-Object System.Security.Principal.NTAccount($ConfiguredUsername)).Translate([System.Security.Principal.SecurityIdentifier]).value;
  $UserProfilePath = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$UserSid' -Name ProfileImagePath).ProfileImagePath

  # Create the .ssh folder and authorized_keys file.
  mkdir $UserProfilePath\.ssh
  Set-Content -Path $UserProfilePath\.ssh\authorized_keys -Value $ConfiguredPublicKey

  # Fix up permissions on authorized_keys
  Import-Module "$env:PROGRAMFILES\OpenSSH-Win64\OpenSSHUtils.psd1 -Force"
  Repair-AuthorizedKeyPermission -FilePath  C:\Users\sshtest_ssouser\.ssh\authorized_keys

  # Should be OK to connect now!
}
```

### With user preconfiguring VM

This assumes the user has already configured the GCE image to install the OpenSSH Server with key-based authentication. In that case the startup script should only have to be:

```
# Should be the Windows account username as specified by the user.
$ConfiguredUsername = "<INJECT VALUE HERE>"
# Should be like "ssh-rsa AAAA..." or whatever the line to be inserted into authorized_keys should be.
$ConfiguredPublicKey = "<INJECT VALUE HERE>"

Write-Output "Setting execution policy for PowerShell scripts...";
Set-ExecutionPolicy Bypass -Scope Process -Force;

# Locate the user's profile path.
$UserSid = (New-Object System.Security.Principal.NTAccount($ConfiguredUsername)).Translate([System.Security.Principal.SecurityIdentifier]).value;
$UserProfilePath = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$UserSid' -Name ProfileImagePath).ProfileImagePath

# Create the .ssh folder and authorized_keys file.
mkdir $UserProfilePath\.ssh
Set-Content -Path $UserProfilePath\.ssh\authorized_keys -Value $ConfiguredPublicKey

# Fix up permissions on authorized_keys
Import-Module "$env:PROGRAMFILES\OpenSSH-Win64\OpenSSHUtils.psd1 -Force"
Repair-AuthorizedKeyPermission -FilePath  C:\Users\sshtest_ssouser\.ssh\authorized_keys
```

## Generated username/password

This is less secure than keypair, but still more secure than fixed username/password. It's a lot easier to get it working with the startup script though, and doesn't require any machine restarts.

### Full automated setup

For when the user wants to use a Windows GCE image that isn't configured with OpenSSH:

```
# Should be the Windows account username as specified by the user.
$ConfiguredUsername = "<INJECT VALUE HERE>"
# Should be generated in the Jenkins plugin and then injected here.
$ConfiguredPassword = "<INJECT VALUE HERE>"

Write-Output "Setting execution policy for PowerShell scripts...";
Set-ExecutionPolicy Bypass -Scope Process -Force;

Write-Output "Installing Chocolatey...";
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

Write-Output "Refreshing environment...";
RefreshEnv.cmd

Write-Output "Installing OpenSSH Server..."
choco install -y openssh -params '"/SSHServerFeature"'
if ($LastExitCode -ne 0) {
  exit 1
}

Write-Output "Setting password of account..."
net user "$ConfiguredUsername" "$ConfiguredPassword"

# Should be OK to connect now!
```

### With user preconfiguring VM

This assumes the user has already configured the GCE image to install the OpenSSH Server. In that case the startup script should only have to be:

```
# Should be the Windows account username as specified by the user.
$ConfiguredUsername = "<INJECT VALUE HERE>"
# Should be generated in the Jenkins plugin and then injected here.
$ConfiguredPassword = "<INJECT VALUE HERE>"

Write-Output "Setting password of account..."
net user "$ConfiguredUsername" "$ConfiguredPassword"

# Should be OK to connect now!
```

## Fixed username/password

This is the least secure, but is required for compatibility with existing environments. It doesn't require the plugin to do any set up on behalf of the user.

**Comment by rachely3n** [comment]
@hach-que I've reviewed the scripts and have been weighing some options. Let's go with releasing the fixed username and password approach hopefully this week. 

Could you please make a new PR without the local SSD changes since I haven't been able to test that feature yet? Thanks!

**Comment by rachely3n** [comment]
Also, really appreciate all the scripts, and we are still looking to see which options we can include later on.

**Comment by ingwarsw** [comment]
@rachely3n local ssd works ok..
On linux you just need to initialise them manually (which is ok)

@rachely3n best option in long term would be allowing to use GCP templates (that would allow removing all rarely used options from plugin itself)

**Comment by evandbrown** [comment]
@rachely3n I made a few tweaks to the "second phase" of @hach-que's helpful scripts. I think there were a few incompatibilities w/ PS 5.x on Server 2016. Can you give this a shot tomorrow?

```
# Should be the Windows account username as specified by the user.
$ConfiguredUsername = "<INJECT VALUE HERE>"
# Should be like "ssh-rsa AAAA..." or whatever the line to be inserted into authorized_keys should be.
$ConfiguredPublicKey = "<INJECT VALUE HERE>"

if (!(Test-Path "$env:SYSTEMDRIVE\_GCE_Jenkins_FirstPhase.txt")) {
  # We are in the first phase where we need to configure PowerShell, install Chocolately, install the OpenSSH Server and the restart the VM.

  Write-Output "Setting execution policy for PowerShell scripts...";
  Set-ExecutionPolicy Bypass -Scope Process -Force;

  Write-Output "Installing Chocolatey...";
  Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

  Write-Output "Refreshing environment...";
  RefreshEnv.cmd

  Write-Output "Installing OpenSSH Server..."
  choco install -y openssh -params '"/SSHServerFeature /KeyBasedAuthenticationFeature"'
  if ($LastExitCode -ne 0) {
    exit 1
  }

  Write-Output "Creating file for next phase on reboot..."
  Set-Content -Path "$env:SYSTEMDRIVE\_GCE_Jenkins_FirstPhase.txt" -Value "OK"

  Write-Output "Restarting the VM..."
  shutdown /t 0 /f /r
} else {
  # We are in the second phase of startup where we need to set up authorized_keys for the specified user.
  $UserSid = Get-WmiObject win32_useraccount -Filter "name = '$ConfiguredUsername'" | select-object sid -ExpandProperty SID
  $UserProfilePath = Get-ItemProperty -Path  "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\ProfileList\$UserSid" -Name ProfileImagePath | select-object profileimagepath -ExpandProperty ProfileImagePath

  # Create the .ssh folder and authorized_keys file.
  mkdir $UserProfilePath\.ssh
  Set-Content -Path $UserProfilePath\.ssh\authorized_keys -Value $ConfiguredPublicKey

  # Fix up permissions on authorized_keys
  Import-Module "$env:PROGRAMFILES\OpenSSH-Win64\OpenSSHUtils.psd1" -Force
  Repair-AuthorizedKeyPermission -FilePath  $UserProfilePath\.ssh\authorized_keys

  # Should be OK to connect now!
}
```

**Comment by rachely3n** [comment]
Closing this PR. See https://github.com/jenkinsci/google-compute-engine-plugin/pull/10 since I had to make some changes on top of your commits. Thanks for contributing! This was super useful.

**Pull request closed without merging**
